[[spring-data-mongodb-reference-documentation]]
= Spring Data MongoDB
:revnumber: {version}
:revdate: {localdate}
:feature-scroll: true

_Spring Data MongoDB provides support for the MongoDB database.
It uses familiar Spring concepts such as a template classes for core API usage and lightweight repository style data access to ease development of applications with a consistent programming model._

[horizontal]
xref:mongodb.adoc[MongoDB] :: MongoDB support and connectivity
xref:repositories.adoc[Repositories] :: Mongo Repositories
xref:observability/observability.adoc[Observability] :: Observability Integration
xref:kotlin.adoc[Kotlin] :: Kotlin support
// xref:migration-guides.adoc[Migration] :: Migration Guides
https://github.com/spring-projects/spring-data-commons/wiki[Wiki] :: What's New, Upgrade Notes, Supported Versions, additional cross-version information.

Mark Pollack; Thomas Risberg; Oliver Gierke; Costin Leau; Jon Brisbin; Thomas Darimont; Christoph Strobl; Mark Paluch; Jay Bryant

(C) 2008-{copyright-year} VMware Inc.

Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.
