[[cassandra.observability]]
= Observability

Getting insights from an application component about its operations, timing and relation to application code is crucial to understand latency.
Spring Data Cassandra ships with a Micrometer instrumentation through the Cassandra driver to collect observations during Cassandra interaction.
Once the integration is set up, Micrometer will create meters and spans (for distributed tracing) for each Cassandra statement.

To enable the instrumentation, apply the following configuration to your application:

====
[source,java]
----
@Configuration
class ObservabilityConfiguration {

  @Bean
  public ObservableCqlSessionFactoryBean observableCqlSession(CqlSessionBuilder builder,
                                                              ObservationRegistry registry) {
    return new ObservableCqlSessionFactoryBean(builder, registry); // <1>
  }

  @Bean
  public ObservableReactiveSessionFactoryBean observableReactiveSession(CqlSession session,
                                                              ObservationRegistry registry) {
    return new ObservableReactiveSessionFactoryBean(session, registry); // <2>
  }
}
----

<1> Wraps the CQL session object to observe Cassandra statement execution.
Also, registers `ObservationRequestTracker.INSTANCE` with the `CqlSessionBuilder`.
<2> Wraps a CQL session object to observe reactive Cassandra statement execution.
====

See also https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/database/#cassandra[OpenTelemetry Semantic Conventions] for further reference.

include::observability/conventions.adoc[leveloffset=+1]

include::observability/metrics.adoc[leveloffset=+1]

include::observability/spans.adoc[leveloffset=+1]
