[[requirements]]
= Requirements

The Spring Data MongoDB 5.x binaries require JDK level 17 and above and https://spring.io/docs[Spring Framework] {springVersion} and above.

[[compatibility.matrix]]
== Compatibility Matrix

[TIP]
====
Please visit https://spring.io/projects/spring-data-mongodb#support[OSS Support] for detailed Spring Data support timelines. +
For the MongoDB Server Support Policy please refer to the https://www.mongodb.com/legal/support-policy/lifecycles[MongoDB Software Lifecycle Schedule].
====

The following compatibility matrix summarizes Spring Data versions and their required minimum MongoDB client version.
Database versions show server generations that pass the Spring Data test suite, older server versions might have difficulties dealing with new/changed commands.
You may use newer server versions unless your application uses functionality that is affected by xref:preface.adoc#compatibility.changes[changes in the MongoDB server].
See also the https://www.mongodb.com/docs/drivers/java/sync/current/compatibility/[official MongoDB driver compatibility matrix] for driver- and server version compatibility.

====
[cols="h,m,m,m", options="header"]
|===

|Spring Data Release Train
|Spring Data MongoDB
|Minimum Driver Version
|Tested Database Versions

|2025.1
|5.0.x
|5.6.x
|6.x to 8.x

|2025.0
|4.5.x
|5.5.x
|6.x to 8.x

|2024.1
|4.4.x
|5.2.x
|4.4.x to 8.x

|2024.0
|4.3.x
|4.11.x & 5.x
|4.4.x to 7.x

|2023.1
|4.2.x
|4.9.x
|4.4.x to 7.x
|===
====

[[compatibility.changes]]
[[compatibility.changes-4.4]]
=== Relevant Changes in MongoDB 4.4

* Fields list must not contain text search score property when no `$text` criteria present. See also https://docs.mongodb.com/manual/reference/operator/query/text/[`$text` operator]
* Sort must not be an empty document when running map reduce.

[[compatibility.changes-4.2]]
=== Relevant Changes in MongoDB 4.2

* Removal of `geoNear` command. See also https://docs.mongodb.com/manual/release-notes/4.2-compatibility/#remove-support-for-the-geonear-command[Removal of `geoNear`]
* Removal of `eval` command. See also https://docs.mongodb.com/manual/release-notes/4.2-compatibility/#remove-support-for-the-eval-command[Removal of `eval`]
