name: Initialize MongoDB
description: 'Initialize a MongoDB server looking up a configuration managed version pointing to a dedicated revision'

inputs:
  managed-versions:
    description: 'managed version json to retrieve the target server version from'
    required: true
  mongodb-server-version:
    description: 'The desired MongoDB Server version'
    required: false
    default: 'latest'
  replica-set:
    description: 'Replica Set Name (if not provided Mongo will be started as a standalone instance)'
    required: false

runs:
  using: composite
  steps:
    - name: Mongo Version
      id: determine-mongo-version
      uses: ./.github/actions/managed-version
      with:
        managed-versions: ${{ inputs.managed-versions }}
        key: '.database.mongodb'
        version: '${{ inputs.mongodb-server-version }}'
    - name: Initialize MongoDB
      uses: ./.github/actions/start-mongodb-server
      with:
        mongo-version: '${{ steps.determine-mongo-version.outputs.managed-version }}'
        replica-set: ${{ inputs.replica-set }}
