name: MongoDB
description: 'Set up a MongoDB server'

inputs:
  mongo-version:
    description: 'MongoDB Server version'
    required: true
  replica-set:
    description: 'Replica Set Name'
    required: false
    default: '_standalone_'
runs:
  using: composite
  steps:
    - name: Start MongoDB Standalone
      shell: bash
      if: ${{ inputs.replica-set == '_standalone_' }}
      run: docker run --rm -d -p 27017:27017 --name mongo mongo:${{ inputs.mongo-version }} --bind_ip_all
    - name: Start MongoDB Replica Set
      shell: bash
      if: ${{ inputs.replica-set != '_standalone_' }}
      run: |
        echo 'replica'
        docker run --rm -d -p 27017:27017 --name mongo mongo:${{ inputs.mongo-version }} --replSet ${{ inputs.replica-set }} --bind_ip_all
        sleep 5 # Give mongo a chance to start up
        docker run --rm mongo:${{ inputs.mongo-version }} mongosh --host 172.17.0.1 --eval 'rs.initiate({_id: "${{ inputs.replica-set }}", members: [{_id: 0, host: "172.17.0.1:27017"}]})'
