= Ahead of Time Optimizations

For a general explanation of what Ahead of Time (AoT) Optimizations Spring Data offers and how to enable them  see
xref:{commons}@data-commons::page$aot.adoc[]

Each module offers optimizations for a slightly different set of repository method.
With Spring Data MongoDb we generally support query methods that are not backed by an xref:repositories/custom-implementations.adoc[implementation fragment], and don't require, with a few limitations detailed below.

**Supported Features**

* Derived `find`, `count`, `exists` and `delete` methods
* Query methods annotated with `@Query` (excluding those containing SpEL)
* Methods annotated with `@Aggregation`, `@Update`, and `@VectorSearch`
* `@Hint`, `@Meta`, and `@ReadPreference` support
* `Page`, `Slice`, and `Optional` return types
* DTO & Interface Projections

**Limitations**

* `@Meta.flags` is not evaluated.
* Limited `Collation` detection.
* No support for in-clauses with pattern matching / case insensitivity

**Excluded methods**

* `CrudRepository` and other base interface methods
* Querydsl and Query by Example methods
* Query Methods obtaining MQL from a file

[TIP]
====
Consider using `Pattern` instead of `String` as parameter type when working with derived queries using the `LIKE` keyword.
[source,java]
----
List<Person> findByLastnameLike(Pattern lastname);
----
====
