[[mongo.query.additional-query-options]]
== Additional Query Options

MongoDB offers various ways of applying meta information, like a comment or a batch size, to a query.Using the `Query` API
directly there are several methods for those options.

[[mongo.query.hints]]
=== Hints

Index hints can be applied in two ways, using the index name or its field definition.

====
[source,java]
----
template.query(Person.class)
    .matching(query("...").withHint("index-to-use"));

template.query(Person.class)
    .matching(query("...").withHint("{ firstname : 1 }"));
----
====

[[mongo.query.cursor-size]]
=== Cursor Batch Size

The cursor batch size defines the number of documents to return in each response batch.
====
[source,java]
----
Query query = query(where("firstname").is("luke"))
    .cursorBatchSize(100)
----
====

[[mongo.query.collation]]
=== Collations

Using collations with collection operations is a matter of specifying a `Collation` instance in your query or operation options, as the following two examples show:

====
[source,java]
----
Collation collation = Collation.of("de");

Query query = new Query(Criteria.where("firstName").is("Amél"))
    .collation(collation);

List<Person> results = template.find(query, Person.class);
----
====

[[mongo.query.read-preference]]
=== Read Preference

The `ReadPreference` to use can be set directly on the `Query` object to be run as outlined below.

====
[source,java]
----
template.find(Person.class)
    .matching(query(where(...)).withReadPreference(ReadPreference.secondary()))
    .all();
----
====

NOTE: The preference set on the `Query` instance will supersede the default `ReadPreference` of `MongoTemplate`.

[[mongo.query.comment]]
=== Comments

Queries can be equipped with comments which makes them easier to look up in server logs.

====
[source,java]
----
template.find(Person.class)
    .matching(query(where(...)).comment("Use the force luke!"))
    .all();
----
====

